# Generated by Django 4.2.6 on 2023-10-14 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUser', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('login_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.login')),
                ('idCliente', models.IntegerField(verbose_name='Id')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
            ],
            bases=('aplic.login',),
        ),
    ]
