# Generated by Django 4.2.6 on 2023-10-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nomeAdmin', models.CharField(max_length=100, verbose_name='Nome')),
                ('idAdmin', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nomeProduto', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('idProduto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('valorProduto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
